# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_insee:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: scratch.sebel.dpr-stat.dpr-psgs.psgs_insee
  id_prefix: 'wiki:'