# @package _group_
dpr_insee:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /media/simon/Samsung_T5/CEDAR/data/datasets/dpr_psgs/psgs_insee.tsv

insee_tables:
  file: /media/simon/Samsung_T5/CEDAR/data/table_metadata.pkl
